### PR TITLE
Added plugin for IO using Raspberry Pi GPIO pins.

### PR DESCRIPTION
**Pull request by bartha-adam**
See config.py.sample for configuration example.
extra: Image for showing score - 10

### CODE REVIEW

**Comment by swehner** [comment]
Hi Adam,

Looks pretty good! Thanks a lot!
I've got a small fix regarding supporting counts up to 10 - there's a change needed in plugins/score.py.
I can add that change after merging your branch.

I have one question, though - to use wiringPi ou're currently required to run foos.py as root, right?
Have you tried using the setup using gpio so running with root is not required http://wiringpi.com/reference/setup/?

**Comment by bartha-adam** [comment]
Stefan,
On my config I have added a game mode up to 10 goals and the counter shows 10 after the last goal of the game.

Yes, sudo is required to run the code, as it is now. I'll take a look if there is a way to run it without sudo and update the PR.

**Comment by swehner** [comment]
Ok, Sounds good.
I'll merge this meanwhile.
If you see that it runs without sudo you can do another PR

**Comment by bartha-adam** [comment]
Stefan,

Unfortunately, wiringPiSetupSys (does not require running as root) is not working with hardware PWM control: "PWM can not be controlled when running in Sys mode." (https://projects.drogon.net/raspberry-pi/wiringpi/functions/)

Observation: sound plugin does not work (at least on my side) when running sudo python3 foos.py.

Any suggestion?

**Comment by bartha-adam** [comment]
One solution would be to setup the PWM from shell script using gpio utility (which runs as root, since it has the setuid flag).

**Comment by swehner** [comment]
Thanks a lot for taking a look at that - it looks pretty good!

**Pull request merged**
