### PR TITLE
Plugin: Trigger foostastic webhook on match end

### PR DESCRIPTION
**Pull request by jaguerra**
Trigger a webhook for foostastic to update data on match end rather than relying on polling.

https://foostastic.herokuapp.com/

:)

### CODE REVIEW

**Comment by dpaneda** [comment]
I think that this is nos foos responsibility, but league system. You can receive a notification from the foos, but the information is not ready yet on the league server. What do you think @swehner ?

**Comment by swehner** [comment]
I'm not sure exactly what Foostastic does, but just having a callback without any data s a bit weird - if it gets all its data from foos-tournament maybe an integration with that might be better.
Maybe you could even send some diff of the data that has changed?

BTW - having an extra thread manually in the plugin is not necessary - just setting thread to True when subscribing should be enough and you could do the upload from the event handling method.

**Comment by jaguerra** [comment]
Foostastic fetches all its data from the foos-tournament API so yes, it makes a lot of sense to integrate the webhook there instead.

I'll give it a spin with suso and close this PR if we find a feasible solution :)

Thanks!

**Comment by dpaneda** [comment]
What do you think if we change this to be a more generic webhook? The foos is mostly a event-driven system, and we could deliver those events via webhook. That seems clean and more useful to @swehner and me. Also that will allow foostastic to have some crazy features like live bets or something. I can refactor the code in that direction if you think that will be useful.

**Comment by danpillay87** [comment]
This would be great, can't seem to work with the league system at the moment as minimal documentation but be cool with generic webhooks could also get it linking with https://github.com/sinnerschrader/digitalfoosball in this way

**Pull request closed without merging**
